services:
  nginx-proxy:
    image: yoldarz/nginx-proxy:1.27.2-vouch-proxy
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ca:/etc/nginx/ca:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - main

  nginx-proxy-acme-companion:
    image: nginxproxy/acme-companion:2.5.0
    restart: unless-stopped
    container_name: nginx-proxy-acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    networks:
      - main

  vouch-proxy:
    image: quay.io/vouch/vouch-proxy:0.45.0
    restart: unless-stopped
    container_name: vouch-proxy
    volumes:
      - vouch-config-data:/config
    enviroment:
      - VOUCH_ALLOWALLUSERS=true
      - VOUCH_COOKIE_DOMAIN=mydomain.com
      - VOUCH_SESSION_KEY=***
      - OAUTH_PROVIDER=azure
      - OAUTH_CLIENT_ID=********-****-****-****-***************
      - OAUTH_CLIENT_SECRET=**********
      - OAUTH_AUTH_URL=https://login.microsoftonline.com/********-****-****-****-***************/oauth2/v2.0/authorize
      - OAUTH_TOKEN_URL=https://login.microsoftonline.com/********-****-****-****-***************/oauth2/v2.0/token
      - OAUTH_USER_INFO_URL=https://graph.microsoft.com/oidc/userinfo
      - OAUTH_SCOPES=openid,profile,email
      - OAUTH_CALLBACK_URL=https://vouch.mydomain.com/auth
      - OAUTH_AZURE_TOKEN=id_token
      - VIRTUAL_HOST=vouch.mydomain.com
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=vouch.mydomain.com
      - VOUCH_LOGLEVEL=debug
    networks:
      - main

volumes:
  certs:
  html:
  acme:
  vouch-config-data:

networks:
  main:
    external: true